<?php
// generated by Poedit from filter-order-history-for-woocommerce-en_US.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en_US','pot-creation-date'=>'2025-08-06 09:22+0200','po-revision-date'=>'2025-08-06 09:22+0200','translation-revision-date'=>'2025-08-06 09:22+0200','project-id-version'=>'OrderFinder - Filter Order History for WooCommerce','x-generator'=>'Poedit 3.6','messages'=>[]];
